name: Release

on:
  push:
    tags:
      - mosh-[0-9]+.[0-9]+-custom
      - mosh-[0-9]+.[0-9]+-custom-r[0-9]+
      - mosh-[0-9]+.[0-9]+.[0-9]+-custom
      - mosh-[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+
      - mosh-[0-9]+.[0-9]+.[0-9]+.[0-9]+rc[0-9]+-custom

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq --no-install-recommends protobuf-compiler libprotobuf-dev libzstd-dev

      - name: Build
        run: ./autogen.sh && ./configure && make dist-xz

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.xz"
